Foo\Match:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
      options:
        unsigned: true
  fields:
    name:
      type: string
      length: 255
      nullable: false
