Foo\OverUnderMatchOutcome:
  type: entity
  fields:
    goalsTotal:
      type: float
      nullable: false
      options:
        unsigned: true
  manyToOne:
    match:
      targetEntity: Foo\Match
      joinColumns:
        match_id:
          referencedColumnName: id
          nullable: false
