Foo\Outcome:
  type: entity
  inheritanceType: JOINED
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
      options:
        unsigned: true
  fields:
    status:
      type: string
      length: 30
      nullable: false
    createdAt:
      type: datetime
      nullable: false
    updatedAt:
      type: datetime
      nullable: false
  discriminatorColumn:
    name: type_id
    type: integer
  discriminatorMap:
    1: Foo\OverUnderMatchOutcome
    2: Foo\ThreeWayMatchOutcome
    3: Foo\CompetitionOutcome
